theme: jekyll-theme-slate

defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "README.html"
      
font:
  enable: true

  # Font settings for Logo
  # Fallback to `global` font settings.
  # The `size` option use `px` as unit
  logo:
    external: true
    size: 50
