theme: jekyll-theme-dinky

title: Data Science Portfolio by Artyom Trofimov

defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "README.html"

h1 {
    font-size: 50px;
    }
